### ISSUE TITLE
Not really an issue but....

### ISSUE THREAD

**Issue by turntablez** [rsim/ruby-plsql-spec#21]
Does any one have a list of the different commands to use in this? I can see the examples but would be handy if there was a cheatsheet for this.
This seems quite geared up to someone who uses ruby and I don't have any experience with it.

Thanks

Alex.

**Comment by jgebal** [comment]
For ruby-plsql-spec itself `plsql-spec --help` shoud do the trick
For RSpec checkout the docs here: https://www.relishapp.com/rspec
For more possible usages (beyond the examples) you might have a look at
https://github.com/rsim/ruby-plsql/tree/master/spec/plsql

**Comment by jgebal** [comment]
Cheat sheet on the other hand seems like a wonderful idea :)
It would take a while, but would be a great contribution. It would be more for ruby-plsql than for ruby-plsql-spec I guess,

**Comment by turntablez** [comment]
thanks jgebal. it would be nice :+1:

**Comment by jgebal** [comment]
I've found a nice tool for generating cheat sheets - https://github.com/Kapeli/cheatset#readme
It would be good to have someone collaborate on this.

**Comment by jgebal** [comment]
I've added a cheat sheet on my [blog](https://www.oraclethoughts.com/ruby-plsql/ruby-plsql-cheatsheet/).
I't not perfect, but may be of use

**Comment by turntablez** [comment]
Thanks Jacek, it looks perfect.

Alex.
