### ISSUE TITLE
Objects not null when passed as parameter.

### ISSUE THREAD

**Issue by wcmatthysen** [rsim/ruby-plsql-spec#7]
Hi there,

When I create the following PL/SQL type:

    CREATE OR REPLACE TYPE PERSON
    IS
      OBJECT
      (
        name     VARCHAR2(255),
        surname  VARCHAR2(255),
        age      NUMBER(10, 0)
      );

and the following procedure for testing purposes:

    CREATE OR REPLACE PROCEDURE test_person(arg PERSON) AS
    BEGIN
      IF arg IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'Person cannot be null.');
      END IF;
    END;

and create the following test:

    require "spec_helper"
    
    describe "People Suite" do
      it "should break when called with a NULL parameter" do
        lambda do
          plsql.test_person(NULL)
        end.should raise_error(/ORA-20001/)
      end
    end

I get the following error when I call the test_person procedure:

   Failures:
   
  1) People Suite should break when called with a NULL parameter
     Failure/Error: lambda do
     expected Exception with message matching /ORA-20001/ but nothing was raised
     # ./spec/Test_spec.rb:5

I would have suspected the test_person to throw an exception when calling with a NULL parameter but it did not. Any help would be  very much appreciated.

Regards,

Wiehann

**Comment by jgebal** [comment]
is it resolved?

**Comment by jgebal** [comment]
Just tested it - it's resolved.
Can be closed.
